config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  get 'posts/index'
  devise_for :users
  resources :users, only: :show do
    collection do
      get 'like'
    end
  end
  root to: 'homes#index'
  resources :posts do
    collection do
      get 'search'
    end
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :homes, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '料理' },
    { id: 3, name: 'プログラミング' },
    { id: 4, name: 'その他' }
    # { id: 5, name: '' },
    # { id: 6, name: '' },
    # { id: 7, name: '' }
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions 
  belongs_to :user
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_one_attached :image

  def self.search(search)
    if search != ''
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_one_attached :image

  
  def liked_by?(post)
    likes.where(post_id: post.id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_side
  
  def after_sign_in_path_for(_resource)
    posts_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :image])
  end

  def set_side
    @users = User.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    if @comment.save
      CommentChannel.broadcast_to @post, { comment: @comment, user: @comment.user, date: @comment.created_at } 
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :move_to_index, only: [:create, :destroy]
    before_action :set_post, only: [:create, :destroy]
  
    def create
      @like = Like.create(post_id: @post.id, user_id: current_user.id)
    end
  
    def destroy
      @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
      @like.destroy
    end
  
    private
  
    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
  
    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.all
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    # 画像複数枚投稿実装の時使用
    # if params[:item][:image_ids]
    #   params[:item][:image_ids].each do |image_id|
    #     image = @item.images.find(image_id)
    #     image.purge
    #   end
    # end
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to posts_path if @post.destroy
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private

  def post_params
    params.require(:post).permit(:genre_id, :title, :detail, :date, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_item
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @email = user.email
    @posts = user.posts
    @image = user.image
    @post = Post.find_by(params[:user_id])
    likes = Like.where(user_id: user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="main-wrapper">
  
  <div class="main-home"></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <header>
      <div class="header-bar">
        <div class="header-left">
          <%= link_to root_path ,id: "logo" do %>
          MemoApp
          <% end %>
        </div>
        <div class="header-right">
          <div class="header-upper">
            <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f| %>
              <%= f.text_field :keyword, placeholder: "商品を検索する", class: "search-text-form" %>
              <%= f.submit "検索", class: "search-btn" %>
            <% end %>
          </div>
          <div class="header-down">
            <% if user_signed_in? %>
              <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: "user-name", id: "name-btn" %>
              <%= link_to "ログアウト", destroy_user_session_path, class: "logout", id: "logout-btn", method: :delete %>
              <%= link_to "メモ一覧", posts_path, class: "post-container" %> 
              <%= link_to "投稿", "/posts/new/", class: "new-post" %> 
            <% else %>
            <div class="user-select" >
              <%= link_to "ログイン", new_user_session_path, class: "login", id: "user-login-btn" %>
            </div>
            <div class="user-select" >
              <%= link_to "新規登録", new_user_registration_path, class: "sign-up", id: "user-signup-btn" %>
            </div>
            <div class="post-container-box">
              <%= link_to "商品一覧", posts_path, class: "post-container", id: "post-box" %>
            <div>
            <% end %> 
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="footer-bar">
        <div class="footer-word"> ~ワケアリ~ </div>
      </div>
    </footer>
  </body>

</html>

app/views/likes/_like.html.erb
          <div id="like-<%= @post.id %>">
            <% if !user_signed_in? %>
              <div class="fa fa-heart like-btn"></div>
            <% elsif current_user.liked_by?(@post) %>
              <%= link_to post_like_path(@post, @post.likes), class: "like-link", method: :delete, remote: true do %>
                <div class="fa fa-heart unlike-btn">お気に入り登録を解除</div>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(@post), class: "like-link", method: :post, remote: true do %>
                <div class="fa fa-heart like-btn">お気に入り登録</div>
              <% end %>
            <% end %>
          </div>

app/views/likes/create.js.erb
document.getElementById('like-<%= @post.id %>').innerHTML = '<%= escape_javascript(render('likes/like', post: @post)) %>'

app/views/likes/destroy.js.erb
document.getElementById('like-<%= @post.id %>').innerHTML = '<%= escape_javascript(render('likes/like', post: @post)) %>'

app/views/posts/edit.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>

  <div class="edit-main">
    <div class="edit-container">
      <h2 class="edit-title">商品の情報を入力</h2>
      <%= form_with model: @post, class: "edit-form", local: true  do |f| %>
    
      <%= render 'shared/error', model: f.object %>
        
        <div class="img-upload">
          <div class="weight-bold-text">
            出品画像
          </div>
          <div class="click-upload" id="click-upload">
            <%= f.file_field :image, id: "post-image" %>
          </div>
        </div>
        <div id="image-list"></div>
        <% image_tag @post.image, id: "image" if @post.image.present? %>
        <div class="new-posts">
          <div class="weight-bold-text">
            商品名
          </div>
          <%= f.text_field :title, class:"posts-text", id:"post-title", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        </div>
        <div class="posts-explain">
          <div class="weight-bold-text">
            商品の説明
          </div>
          <%= f.text_area :detail, class:"posts-text", id:"post-info", placeholder: "注)カテゴリーで複数種混合を選択した場合は内容を説明欄に記載してください（必須 1,000文字まで)" , rows:"7" , maxlength:"1000" %>
        </div>
        <div class="posts-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="form">
            <div class="weight-bold-text">
              カテゴリー
            </div>
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"post-genre"}) %>
          </div>
        </div>
        <div class="date">
          <h3 class="f-word">開催日時</h3>
          <%= f.datetime_field :date, {include_blank: true}%>
        </div>

            <%# 後で使用する %>
            <%# <script src="javascript/price.js"></script> %>
        <div class="post-btn-contents">
          <div class="post-btn-content">
            <%= f.submit "投稿する", class:"post-btn" %>
          </div>
          <div class="back-btn-content">
            <%=link_to '戻る', posts_path, class:"back-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main-wrapper">
  
  <%= render "shared/side"%>
  
  <div class="post-contents">
    <h2 class="main-title">メモ一覧</h2>
    <ul class="post-lists">
      <% @posts.each do |post| %>
        <li class="list">
          <%= link_to post_path(post.id) do %>
            <div class="post-img-content">
              <%= image_tag post.image, class: "post-images" if post.image.present? %>
            </div>
            <div class='post-info'>
              <h3 class='post-title'>
                <%= "#{post.title}" %>
              </h3>
              <div class='post-detail'>
                <span><%= "#{post.detail}" %></span>  
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
      <% if @posts.length == 0 %> 
        <li class='list'>
          <%= link_to '#' do %>
            <div class="post-img-content">
              <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "post-images" %> 
            </div>  
            <div class='post-info'>
              <h3 class='post-title'>
                  商品を出品してださい。
              </h3>
            </div> 
          <% end %> 
        </li>
      <% end %> 
    </ul>
    <%# <div class="page-container">
      <%= paginate @posts, class: "page" %> %>
    <%# </div> %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>

  <div class="sell-main">
    <div class="sell-container">
      <h2 class="sell-title">商品の情報を入力</h2>
      <%= form_with model: @post, class: "sell-form", local: true  do |f| %>
    
      <%= render 'shared/error', model: f.object %>
        
        <div class="img-upload">
          <div class="weight-bold-text">
            出品画像
          </div>
          <div class="click-upload" id="click-upload">
            <%= f.file_field :image, id: "post-image" %>
          </div>
        </div>
        <div id="image-list"></div> 
        <% image_tag @post.image, id: "image" if @post.image.present? %>
        <div class="new-posts">
          <div class="weight-bold-text">
            商品名
          </div>
          <%= f.text_field :title, class:"posts-text", id:"post-title", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        </div>
        <div class="posts-explain">
          <div class="weight-bold-text">
            商品の説明
          </div>
          <%= f.text_area :detail, class:"posts-text", id:"post-info", placeholder: "注)カテゴリーで複数種混合を選択した場合は内容を説明欄に記載してください（必須 1,000文字まで)" , rows:"7" , maxlength:"1000" %>
        </div>
        <div class="posts-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="form">
            <div class="weight-bold-text">
              カテゴリー
            </div>
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"post-genre"}) %>
          </div>
        </div>
        <div class="date">
          <h3 class="f-word">開催日時</h3>
          <%= f.datetime_field :date, {include_blank: true}%>
        </div>
        <div class="post-btn-contents">
          <div class="post-btn-content">
            <%= f.submit "投稿する", class:"post-btn" %>
          </div>
          <div class="back-btn-content">
            <%=link_to '戻る', posts_path, class:"back-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="main-wrapper">
  
  <%= render "shared/side"%>
  
  <div class="post-contents">
    <h2 class="main-title">検索一覧</h2>
    <ul class="post-lists">
      <% @posts.each do |post| %>
        <li class="list">
          <%= link_to post_path(post.id) do %>
            <div class="post-img-content">
              <%= image_tag post.image, class: "post-images" if post.image.present? %>
            </div>
            <div class='post-info'>
              <h3 class='post-title'>
                <%= "#{post.title}" %>
              </h3>
              <div class='post-detail'>
                <span><%= "#{post.detail}" %></span>  
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
      <% if @posts.length == 0 %> 
        <li class='list'>
          <%= link_to '#' do %>
            <div class="post-img-content">
              <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "post-images" %> 
            </div>  
            <div class='post-info'>
              <h3 class='post-title'>
                  商品を出品してださい。
              </h3>
            </div> 
          <% end %> 
        </li>
      <% end %> 
    </ul>
    <%# <div class="page-container">
      <%= paginate @posts, class: "page" %> %>
    <%# </div> %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>
  
  <div class="post-show">
    <div class="post-show-container">
      <div class="post-box">
        <h2 class="post-show-name">
          <%= "#{@post.title}" %>
        </h2>
        <div class="post-img-content">
          <%= image_tag @post.image, class:"post-box-img" %>
        </div>

        <%= render('likes/like', post: @post) %>

        <div class="post-command">
          <% if user_signed_in? %>
            <% if current_user.id == @post.user_id %>
              <%= link_to "編集", edit_post_path(@post.id), method: :get, class: "post-edit-btn" %>
              <p class="or-text">or</p>
              <%= link_to "削除", post_path(@post.id), method: :delete, class: "post-destroy-btn" %>
            <% end %>
          <% end %>
        </div>
        <div class="post-description-box">
          <span><%= "#{@post.detail}" %></span>
        </div>
        <div class="post-description-box">
          <span><%= "#{@post.genre.name}" %></span>
        </div>
        <div class="post-description-box">
          <span><%= "#{@post.date}" %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with model: [@post, @comment], id: "comment-form" do |f| %>
        <%= f.text_area :text , class: "comment-text"%>
        <%= f.submit "コメントをする", class: "comment-submit" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %> 
  </div> 

  <%= render "shared/comment" %>

</div>
    

app/views/shared/_comment.html.erb
  <div class="comments">
    <h4>＜コメント一覧＞</h4>
    <div id="comments">
      <% @post.comments.reverse_each do |comment| %>
        <div class="comment">
          <p class="user-info">
            <strong><%= link_to "#{comment.user.nickname}", "/users/#{comment.user_id}" %>:</strong>
            <%= comment.text%>
          </p>
          <p>
            <%= comment.created_at %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

app/views/shared/_error.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_side.html.erb
  <div class="side">
    <div class="user-names">出品者様一覧</div>
    <ul class="side-names">
      <% @users.each do |user| %>
        <li class="side-name">           
        <%= link_to user_path(user.id), class: "side-user-name" do %>
          <%= "#{user.nickname}様" %>
        <% end %>
        </li>
      <% end %>
    </ul>
    <div class="date-time-box">
      <div id="date-time"></div>
    </div>
    <script type="text/javascript">
      setInterval('clock()', 500);
      function clock() {
        document.getElementById("date-time").innerHTML = showClock();
      }
      function showClock() {
        var now = new Date();
        var Year = now.getFullYear();
        var Month = ("0" + (now.getMonth()+1)).slice(-2);
        var Day = ("0" + now.getDate()).slice(-2);
        var you = now.getDay(); 
        var Hour = ("0" + now.getHours()).slice(-2);
        var Min = ("0" + now.getMinutes()).slice(-2);
        var Sec = ("0" + now.getSeconds()).slice(-2);

        var youbi = new Array("日","月","火","水","木","金","土");

        var s = Year + "年" + Month + "月" + Day + "日(" + youbi[you] + ")" + Hour + ":" + Min + ":" + Sec;
        return s;
      }
    </script>
  </div>

app/views/users/show.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>

  <div class="user-show-main">
    <div class="user-show-box">
      <% if user_signed_in?%>
        <div class="user-show-status-box">
          <div class="user-status">
            <div class="post-img-content">
              <%= image_tag @image, class:"post-box-img" %>
            </div>
            <h2 class="user-nickname"> 
              <%= @nickname %>
            </h2>
            <% if @email == current_user.email %>
              <p class="user-email">
                <%= @email %>
              </p>
              <div class="user-select-btn-container">
                <div class="user-edit-btn">
                  <%= link_to "編集", "/users/edit" %>
                </div> 
                <div class="user-delete-btn"> 
                  <%= link_to "退会", user_registration_path, method: :delete %>
                </div>
              </div>
            <% end %> 
          </div>
        </div>
      <% end %>
      <div class="user-show">
        <h2 class="main-title"><%= @nickname %>さんの商品一覧</h2>
        <ul class="user-post-lists">
          <% @posts.each do |post| %> 
            <li class="user-post-list">
              <%= link_to post_path(post.id) do %>
                <div class="post-img-content">
                  <%= image_tag post.image, class: "post-images" if post.image.present? %> 
                </div>
                <div class='post-info'>
                  <h3 class='post-name'>
                    <%= "#{post.title}" %>
                  </h3>
                </div>
              <% end %>
            </li>
          <% end %> 
        </ul>
      </div>
      <h2 class="main-title"><%= @nickname %>さんのお気に入り一覧</h2>
        <ul class="user-post-lists">
          <% @like_posts.each do |like| %> 
            <li class="user-post-list">
              <%= link_to post_path(like.id) do %>
                <div class="post-img-content">
                  <%= image_tag post.image, class: "post-images" if post.image.present? %> 
                </div>
                <div class='post-info'>
                  <h3 class='post-name'>
                    <%= "#{like.title}" %>
                  </h3>
                </div>
              <% end %>
            </li>
          <% end %> 
        </ul>
      </div>

    </div>
  </div>
</div>